/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NetworkRouteRouteImport } from './routes/$network/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NetworkIndexRouteImport } from './routes/$network/index'
import { Route as NetworkSuperAppsRouteImport } from './routes/$network/super-apps'
import { Route as NetworkProtocolRouteImport } from './routes/$network/protocol'
import { Route as NetworkLiquidationsRouteImport } from './routes/$network/liquidations'
import { Route as NetworkSupertokensIndexRouteImport } from './routes/$network/supertokens.index'
import { Route as NetworkSupertokensAddressRouteImport } from './routes/$network/supertokens.$address'
import { Route as NetworkStreamsIdRouteImport } from './routes/$network/streams.$id'
import { Route as NetworkPoolsAddressRouteImport } from './routes/$network/pools.$address'
import { Route as NetworkAccountsAddressRouteImport } from './routes/$network/accounts.$address'
import { Route as NetworkPoolsAddressMembersMemberAddressRouteImport } from './routes/$network/pools.$address.members.$memberAddress'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRouteRoute = NetworkRouteRouteImport.update({
  id: '/$network',
  path: '/$network',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkIndexRoute = NetworkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NetworkRouteRoute,
} as any)
const NetworkSuperAppsRoute = NetworkSuperAppsRouteImport.update({
  id: '/super-apps',
  path: '/super-apps',
  getParentRoute: () => NetworkRouteRoute,
} as any)
const NetworkProtocolRoute = NetworkProtocolRouteImport.update({
  id: '/protocol',
  path: '/protocol',
  getParentRoute: () => NetworkRouteRoute,
} as any)
const NetworkLiquidationsRoute = NetworkLiquidationsRouteImport.update({
  id: '/liquidations',
  path: '/liquidations',
  getParentRoute: () => NetworkRouteRoute,
} as any)
const NetworkSupertokensIndexRoute = NetworkSupertokensIndexRouteImport.update({
  id: '/supertokens/',
  path: '/supertokens/',
  getParentRoute: () => NetworkRouteRoute,
} as any)
const NetworkSupertokensAddressRoute =
  NetworkSupertokensAddressRouteImport.update({
    id: '/supertokens/$address',
    path: '/supertokens/$address',
    getParentRoute: () => NetworkRouteRoute,
  } as any)
const NetworkStreamsIdRoute = NetworkStreamsIdRouteImport.update({
  id: '/streams/$id',
  path: '/streams/$id',
  getParentRoute: () => NetworkRouteRoute,
} as any)
const NetworkPoolsAddressRoute = NetworkPoolsAddressRouteImport.update({
  id: '/pools/$address',
  path: '/pools/$address',
  getParentRoute: () => NetworkRouteRoute,
} as any)
const NetworkAccountsAddressRoute = NetworkAccountsAddressRouteImport.update({
  id: '/accounts/$address',
  path: '/accounts/$address',
  getParentRoute: () => NetworkRouteRoute,
} as any)
const NetworkPoolsAddressMembersMemberAddressRoute =
  NetworkPoolsAddressMembersMemberAddressRouteImport.update({
    id: '/members/$memberAddress',
    path: '/members/$memberAddress',
    getParentRoute: () => NetworkPoolsAddressRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$network': typeof NetworkRouteRouteWithChildren
  '/settings': typeof SettingsRoute
  '/$network/liquidations': typeof NetworkLiquidationsRoute
  '/$network/protocol': typeof NetworkProtocolRoute
  '/$network/super-apps': typeof NetworkSuperAppsRoute
  '/$network/': typeof NetworkIndexRoute
  '/$network/accounts/$address': typeof NetworkAccountsAddressRoute
  '/$network/pools/$address': typeof NetworkPoolsAddressRouteWithChildren
  '/$network/streams/$id': typeof NetworkStreamsIdRoute
  '/$network/supertokens/$address': typeof NetworkSupertokensAddressRoute
  '/$network/supertokens/': typeof NetworkSupertokensIndexRoute
  '/$network/pools/$address/members/$memberAddress': typeof NetworkPoolsAddressMembersMemberAddressRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/$network/liquidations': typeof NetworkLiquidationsRoute
  '/$network/protocol': typeof NetworkProtocolRoute
  '/$network/super-apps': typeof NetworkSuperAppsRoute
  '/$network': typeof NetworkIndexRoute
  '/$network/accounts/$address': typeof NetworkAccountsAddressRoute
  '/$network/pools/$address': typeof NetworkPoolsAddressRouteWithChildren
  '/$network/streams/$id': typeof NetworkStreamsIdRoute
  '/$network/supertokens/$address': typeof NetworkSupertokensAddressRoute
  '/$network/supertokens': typeof NetworkSupertokensIndexRoute
  '/$network/pools/$address/members/$memberAddress': typeof NetworkPoolsAddressMembersMemberAddressRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$network': typeof NetworkRouteRouteWithChildren
  '/settings': typeof SettingsRoute
  '/$network/liquidations': typeof NetworkLiquidationsRoute
  '/$network/protocol': typeof NetworkProtocolRoute
  '/$network/super-apps': typeof NetworkSuperAppsRoute
  '/$network/': typeof NetworkIndexRoute
  '/$network/accounts/$address': typeof NetworkAccountsAddressRoute
  '/$network/pools/$address': typeof NetworkPoolsAddressRouteWithChildren
  '/$network/streams/$id': typeof NetworkStreamsIdRoute
  '/$network/supertokens/$address': typeof NetworkSupertokensAddressRoute
  '/$network/supertokens/': typeof NetworkSupertokensIndexRoute
  '/$network/pools/$address/members/$memberAddress': typeof NetworkPoolsAddressMembersMemberAddressRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$network'
    | '/settings'
    | '/$network/liquidations'
    | '/$network/protocol'
    | '/$network/super-apps'
    | '/$network/'
    | '/$network/accounts/$address'
    | '/$network/pools/$address'
    | '/$network/streams/$id'
    | '/$network/supertokens/$address'
    | '/$network/supertokens/'
    | '/$network/pools/$address/members/$memberAddress'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/$network/liquidations'
    | '/$network/protocol'
    | '/$network/super-apps'
    | '/$network'
    | '/$network/accounts/$address'
    | '/$network/pools/$address'
    | '/$network/streams/$id'
    | '/$network/supertokens/$address'
    | '/$network/supertokens'
    | '/$network/pools/$address/members/$memberAddress'
  id:
    | '__root__'
    | '/'
    | '/$network'
    | '/settings'
    | '/$network/liquidations'
    | '/$network/protocol'
    | '/$network/super-apps'
    | '/$network/'
    | '/$network/accounts/$address'
    | '/$network/pools/$address'
    | '/$network/streams/$id'
    | '/$network/supertokens/$address'
    | '/$network/supertokens/'
    | '/$network/pools/$address/members/$memberAddress'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NetworkRouteRoute: typeof NetworkRouteRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$network': {
      id: '/$network'
      path: '/$network'
      fullPath: '/$network'
      preLoaderRoute: typeof NetworkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$network/': {
      id: '/$network/'
      path: '/'
      fullPath: '/$network/'
      preLoaderRoute: typeof NetworkIndexRouteImport
      parentRoute: typeof NetworkRouteRoute
    }
    '/$network/super-apps': {
      id: '/$network/super-apps'
      path: '/super-apps'
      fullPath: '/$network/super-apps'
      preLoaderRoute: typeof NetworkSuperAppsRouteImport
      parentRoute: typeof NetworkRouteRoute
    }
    '/$network/protocol': {
      id: '/$network/protocol'
      path: '/protocol'
      fullPath: '/$network/protocol'
      preLoaderRoute: typeof NetworkProtocolRouteImport
      parentRoute: typeof NetworkRouteRoute
    }
    '/$network/liquidations': {
      id: '/$network/liquidations'
      path: '/liquidations'
      fullPath: '/$network/liquidations'
      preLoaderRoute: typeof NetworkLiquidationsRouteImport
      parentRoute: typeof NetworkRouteRoute
    }
    '/$network/supertokens/': {
      id: '/$network/supertokens/'
      path: '/supertokens'
      fullPath: '/$network/supertokens/'
      preLoaderRoute: typeof NetworkSupertokensIndexRouteImport
      parentRoute: typeof NetworkRouteRoute
    }
    '/$network/supertokens/$address': {
      id: '/$network/supertokens/$address'
      path: '/supertokens/$address'
      fullPath: '/$network/supertokens/$address'
      preLoaderRoute: typeof NetworkSupertokensAddressRouteImport
      parentRoute: typeof NetworkRouteRoute
    }
    '/$network/streams/$id': {
      id: '/$network/streams/$id'
      path: '/streams/$id'
      fullPath: '/$network/streams/$id'
      preLoaderRoute: typeof NetworkStreamsIdRouteImport
      parentRoute: typeof NetworkRouteRoute
    }
    '/$network/pools/$address': {
      id: '/$network/pools/$address'
      path: '/pools/$address'
      fullPath: '/$network/pools/$address'
      preLoaderRoute: typeof NetworkPoolsAddressRouteImport
      parentRoute: typeof NetworkRouteRoute
    }
    '/$network/accounts/$address': {
      id: '/$network/accounts/$address'
      path: '/accounts/$address'
      fullPath: '/$network/accounts/$address'
      preLoaderRoute: typeof NetworkAccountsAddressRouteImport
      parentRoute: typeof NetworkRouteRoute
    }
    '/$network/pools/$address/members/$memberAddress': {
      id: '/$network/pools/$address/members/$memberAddress'
      path: '/members/$memberAddress'
      fullPath: '/$network/pools/$address/members/$memberAddress'
      preLoaderRoute: typeof NetworkPoolsAddressMembersMemberAddressRouteImport
      parentRoute: typeof NetworkPoolsAddressRoute
    }
  }
}

interface NetworkPoolsAddressRouteChildren {
  NetworkPoolsAddressMembersMemberAddressRoute: typeof NetworkPoolsAddressMembersMemberAddressRoute
}

const NetworkPoolsAddressRouteChildren: NetworkPoolsAddressRouteChildren = {
  NetworkPoolsAddressMembersMemberAddressRoute:
    NetworkPoolsAddressMembersMemberAddressRoute,
}

const NetworkPoolsAddressRouteWithChildren =
  NetworkPoolsAddressRoute._addFileChildren(NetworkPoolsAddressRouteChildren)

interface NetworkRouteRouteChildren {
  NetworkLiquidationsRoute: typeof NetworkLiquidationsRoute
  NetworkProtocolRoute: typeof NetworkProtocolRoute
  NetworkSuperAppsRoute: typeof NetworkSuperAppsRoute
  NetworkIndexRoute: typeof NetworkIndexRoute
  NetworkAccountsAddressRoute: typeof NetworkAccountsAddressRoute
  NetworkPoolsAddressRoute: typeof NetworkPoolsAddressRouteWithChildren
  NetworkStreamsIdRoute: typeof NetworkStreamsIdRoute
  NetworkSupertokensAddressRoute: typeof NetworkSupertokensAddressRoute
  NetworkSupertokensIndexRoute: typeof NetworkSupertokensIndexRoute
}

const NetworkRouteRouteChildren: NetworkRouteRouteChildren = {
  NetworkLiquidationsRoute: NetworkLiquidationsRoute,
  NetworkProtocolRoute: NetworkProtocolRoute,
  NetworkSuperAppsRoute: NetworkSuperAppsRoute,
  NetworkIndexRoute: NetworkIndexRoute,
  NetworkAccountsAddressRoute: NetworkAccountsAddressRoute,
  NetworkPoolsAddressRoute: NetworkPoolsAddressRouteWithChildren,
  NetworkStreamsIdRoute: NetworkStreamsIdRoute,
  NetworkSupertokensAddressRoute: NetworkSupertokensAddressRoute,
  NetworkSupertokensIndexRoute: NetworkSupertokensIndexRoute,
}

const NetworkRouteRouteWithChildren = NetworkRouteRoute._addFileChildren(
  NetworkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NetworkRouteRoute: NetworkRouteRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
